### ISSUE TITLE
Installing errors for Giotto suite 

### ISSUE THREAD

**Issue by weifangliu** [drieslab/Giotto_site_suite#30]
Hi,

I was trying to install Giotto suite 2.0.0.997 but ran into this error:
`Error: C:/Users/Weifang/AppData/Local/Temp/RtmpmSVWlL/R.INSTALL4cc07985f8/Giotto/man/reconnect_image_object.Rd:26: Bad \link text`

Do you have any ideas?

Thanks,
Weifang

**Comment by RubD** [comment]
Hi Weifang, this is the repo for the website associated with giotto suite. Which command did you use to install the suite branch of Giotto?
Ruben

**Comment by weifangliu** [comment]
Hi Ruben, thanks for your quick response. I was following [https://giottosuite.com/articles/getting_started.html#getting-started] and I used `remotes::install_github("RubD/Giotto@suite")` to install. 

It also gave me a bunch of warning messages during installation: 

> Rd warning: C:/Users/Weifang/AppData/Local/Temp/RtmpmSVWlL/R.INSTALL4cc07985f8/Giotto/man/annotateSpatialGrid.Rd:22: missing link 'showGrids'
Rd warning: C:/Users/Weifang/AppData/Local/Temp/RtmpmSVWlL/R.INSTALL4cc07985f8/Giotto/man/cellProximitySpatPlot.Rd:13: missing link 'cellProximitySpatPlot2D'
Rd warning: C:/Users/Weifang/AppData/Local/Temp/RtmpmSVWlL/R.INSTALL4cc07985f8/Giotto/man/cellProximitySpatPlot.Rd:59: missing link 'cellProximitySpatPlot2D'
.....

**Comment by RubD** [comment]
@jiajic I think something might have gone wrong when updating the documentation. Could you help check?

**Comment by RubD** [comment]
There seems to be an issue with the documentation on Windows machines. We're trying to fix this right now.

**Comment by weifangliu** [comment]
Thanks for following up. Yes I am using a Windows machine.

**Comment by jiajic** [comment]
Hi @weifangliu, we made a push today and Giotto is installing on Windows without warning messages now on my end.
Thanks for bringing this to our attention!

Thanks,
George

**Comment by weifangliu** [comment]
Thank you for the update! I can successfully install the latest Giotto suite on my Windows machine.
